# Generated by Django 5.0.4 on 2024-04-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_two', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytwo',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
