# Generated by Django 5.0.4 on 2024-04-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_two', '0003_surveytwo_owner_alter_surveytwo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveytwo',
            name='owner',
        ),
    ]
