# Generated by Django 5.0.4 on 2024-04-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_one', '0002_questionone_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionone',
            name='owner',
        ),
    ]
